version: '3.4'

services:  
  docker.api:
    image: andrecini/devops_api:dev
    build:
      context: .
      dockerfile: Docker.API/Dockerfile
    depends_on: 
      - database
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development

  database:
    image: mysql:5.5
    container_name: mysql
    ports:
      - "3307:3307"
    expose: 
      - 3306   
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: andrecini
      MYSQL_USER: root
      MYSQL_PASSWORD: andrecini
      MYSQL_DATABASE: devops
volumes:
  db-volume:
