name: Build Docker Compose

on:
  push:
    branches:
      - main  # Defina a branch onde deseja que o build ocorra

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Compose
        run: |
          docker-compose build
